'use strict';
/** playbooks/render-md.js — renders docs/playbooks/*.md from definitions.js. `node server/playbooks/render-md.js` writes; test/playbooks.test.js checks they match. */
const fs = require('node:fs');
const path = require('node:path');
const { PLAYBOOKS } = require('./definitions');

const DIR = path.join(__dirname, '..', '..', 'docs', 'playbooks');

function renderPlaybook(p) {
  const lines = [
    `# ${p.title}`, '',
    '<!-- Generated from server/playbooks/definitions.js by server/playbooks/render-md.js. Edit the definition, not this file. -->', '',
    `**When to use:** ${p.whenToUse}`, '', p.background, '', '## Steps', '',
  ];
  p.steps.forEach((s, i) => {
    lines.push(`${i + 1}. [ ] **${s.title}** (\`${s.id}\`)`);
    if (s.detail) lines.push(`   ${s.detail}`);
    if (s.check) lines.push(`   _Live check: \`${s.check}\`._`);
  });
  lines.push('', 'Policy claims above say `verified 2026-10-05 - <url>` only where that page was read; anything else is `assumed, unverified`.', '');
  return lines.join('\n');
}

function renderIndex() {
  return ['# Operator playbooks', '', '<!-- Generated by server/playbooks/render-md.js. -->', '',
    ...PLAYBOOKS.map(p => `- [${p.title}](${p.id}.md): ${p.whenToUse}`), ''].join('\n');
}

function files() {
  const out = { 'README.md': renderIndex() };
  for (const p of PLAYBOOKS) out[`${p.id}.md`] = renderPlaybook(p);
  return out;
}

function writeAll(dir = DIR) {
  fs.mkdirSync(dir, { recursive: true });
  for (const [name, text] of Object.entries(files())) fs.writeFileSync(path.join(dir, name), text);
}

if (require.main === module) { writeAll(); console.log(`wrote ${Object.keys(files()).length} files to ${DIR}`); }
module.exports = { renderPlaybook, renderIndex, files, writeAll, DIR };
